repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        exclude: '^tests/cassettes'
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '^.+?\.json$'
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        exclude: '^tests/cassettes'
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        # Expects shellcheck to be installed on the system
        # https://github.com/koalaman/shellcheck#installing
