name: Update community pull requests spreadsheet
on:
  pull_request_target:
    types: [assigned,unassigned,opened,closed,reopened]
  workflow_call:
    secrets:
      LE_BOT_APP_ID:
        description: "GitHub App ID for authentication"
        required: true
      LE_BOT_PRIVATE_KEY:
        description: "GitHub App Private Key for authentication"
        required: true
      CONTRIBUTIONS_SPREADSHEET_ID:
        required: true
      CONTRIBUTIONS_SHEET_NAME:
        required: true
      GH_UPLOADER_GCP_SA_CREDENTIALS:
        required: true

jobs:
  check-if-contributor:
    name: Check if author is contributor
    uses: learningequality/.github/.github/workflows/is-contributor.yml@main
    secrets:
      LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
      LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
    with:
      username: ${{ github.event.pull_request.user.login }}
      author_association: ${{ github.event.pull_request.author_association }}

  update-spreadsheet:
    needs: [check-if-contributor]
    runs-on: ubuntu-latest
    if: ${{ needs.check-if-contributor.outputs.is_contributor == 'true' }}
    steps:
      # Checkout the code for the test-actions repository
    - name: Checkout code
      uses: actions/checkout@v4
      
      # Checkout the .github repository
    - name: Checkout .github repository
      uses: actions/checkout@v4
      with:
        repository: learningequality/.github
        path: .github-repo
      
      # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
      # Install dependencies from the .github repository
    - name: Install dependencies
      run: npm install
      working-directory: .github-repo 
      
      # Run the update-pr-spreadsheet script
    - name: Run script
      run: node .github-repo/scripts/update-pr-spreadsheet.js
      env:
        SPREADSHEET_ID: ${{ secrets.CONTRIBUTIONS_SPREADSHEET_ID }}
        SHEET_NAME: ${{ secrets.CONTRIBUTIONS_SHEET_NAME }}
        GOOGLE_CREDENTIALS: ${{ secrets.GH_UPLOADER_GCP_SA_CREDENTIALS }}
        GITHUB_EVENT: ${{ toJson(github.event) }}
